// Generated by CoffeeScript 1.6.2
(function() {
  var Minefield;

  Minefield = (function() {
    function Minefield(window, game_status_changed_func) {
      this.window = window;
      this.game_status_changed_func = game_status_changed_func != null ? game_status_changed_func : null;
      this.game_status = -1;
      this.table = null;
      this.on_click_func = null;
      this.on_rclick_func = null;
    }

    Minefield.prototype.new_table = function() {
      var x, y, _i, _ref, _results;

      _results = [];
      for (x = _i = 1, _ref = this.columns; 1 <= _ref ? _i <= _ref : _i >= _ref; x = 1 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;

          _results1 = [];
          for (y = _j = 1, _ref1 = this.rows; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 1 <= _ref1 ? ++_j : --_j) {
            _results1.push(0);
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Minefield.prototype.init_board = function(columns, rows, num_mines, max_mines) {
      this.columns = columns;
      this.rows = rows;
      this.num_mines = num_mines;
      this.max_mines = max_mines != null ? max_mines : 1;
      return this.reset_board();
    };

    Minefield.prototype.reset_board = function() {
      var on_click_to, on_rclick_to, td, tr, x, y, _i, _j, _ref, _ref1;

      if (this.table) {
        this.window.removeChild(this.table);
        this.game_status = -1;
        this.table = null;
      }
      this.table = document.createElement('table');
      this.table.setAttribute("class", "minetable");
      this.num_flags = 0;
      this.flags = this.new_table();
      this.near_flags = this.new_table();
      this.tds = this.new_table();
      for (y = _i = 0, _ref = this.rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
        tr = document.createElement('tr');
        for (x = _j = 0, _ref1 = this.columns - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
          td = document.createElement('td');
          td.setAttribute("id", "x" + x + "y" + y);
          on_click_to = function(x_, y_, self) {
            return function() {
              self.on_click(x_, y_);
              return false;
            };
          };
          td.onclick = on_click_to(x, y, this);
          on_rclick_to = function(x_, y_, self) {
            return function() {
              self.on_rclick(x_, y_);
              return false;
            };
          };
          td.oncontextmenu = on_rclick_to(x, y, this);
          this.tds[x][y] = td;
          tr.appendChild(td);
        }
        this.table.appendChild(tr);
      }
      this.window.appendChild(this.table);
      this.init_mines();
      return this.on_game_status_changed();
    };

    Minefield.prototype.init_mines = function() {
      var n, n_max, num_mine_created, x, y;

      this.mines = this.new_table();
      this.remaining = this.rows * this.columns;
      num_mine_created = 0;
      while (num_mine_created < this.num_mines) {
        x = Math.floor(Math.random() * this.columns);
        y = Math.floor(Math.random() * this.rows);
        if (this.mines[x][y] < this.max_mines) {
          n_max = this.max_mines - this.mines[x][y];
          n_max = Math.min(n_max, this.num_mines - num_mine_created);
          n = Math.floor(Math.random() * n_max) + 1;
          if (this.mines[x][y] === 0) {
            this.remaining -= 1;
          }
          this.mines[x][y] += n;
          num_mine_created += n;
        }
      }
      this.near_mines = this.generate_near_mines(this.mines);
      return this.game_status = 1;
    };

    Minefield.prototype.generate_near_mines = function(mines) {
      var near_mines, nx, ny, x, y, _i, _j, _k, _len, _ref, _ref1, _ref2, _ref3;

      near_mines = this.new_table();
      for (x = _i = 0, _ref = this.columns - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        for (y = _j = 0, _ref1 = this.rows - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          _ref2 = this.near_positions(x, y);
          for (_k = 0, _len = _ref2.length; _k < _len; _k++) {
            _ref3 = _ref2[_k], nx = _ref3[0], ny = _ref3[1];
            near_mines[nx][ny] += mines[x][y];
          }
        }
      }
      return near_mines;
    };

    Minefield.prototype.shift_table = function(table, dx, dy) {
      var new_table, new_x, new_y, nx, ny, _i, _j, _ref, _ref1;

      new_table = this.new_table();
      for (ny = _i = 0, _ref = this.rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; ny = 0 <= _ref ? ++_i : --_i) {
        for (nx = _j = 0, _ref1 = this.columns - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; nx = 0 <= _ref1 ? ++_j : --_j) {
          new_x = (nx + dx + 2 * this.columns) % this.columns;
          new_y = (ny + dy + 2 * this.rows) % this.rows;
          new_table[new_x][new_y] = table[nx][ny];
        }
      }
      return new_table;
    };

    Minefield.prototype.get_class = function(x, y) {
      var td_class;

      td_class = this.tds[x][y].getAttribute("class");
      if (td_class === null || td_class === "") {
        null;
      }
      return td_class;
    };

    Minefield.prototype.set_class = function(x, y, val) {
      if (val === null) {
        return this.tds[x][y].removeAttribute("class");
      } else {
        return this.tds[x][y].setAttribute("class", val);
      }
    };

    Minefield.prototype.near_positions = function(x, y) {
      var nx, ny, ret, _i, _j, _ref, _ref1, _ref2, _ref3;

      ret = [];
      for (nx = _i = _ref = x - 1, _ref1 = x + 1; _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; nx = _ref <= _ref1 ? ++_i : --_i) {
        for (ny = _j = _ref2 = y - 1, _ref3 = y + 1; _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; ny = _ref2 <= _ref3 ? ++_j : --_j) {
          if (nx === x && ny === y) {
            continue;
          }
          if (nx >= this.columns || nx < 0 || ny >= this.rows || ny < 0) {
            continue;
          }
          ret.push([nx, ny]);
        }
      }
      return ret;
    };

    Minefield.prototype.on_click = function(x, y) {
      var old_game_status;

      old_game_status = this.game_status;
      if (this.game_status < 0) {
        return;
      }
      if (this.game_status === 1) {
        this.start(x, y);
      }
      if (this.expand(x, y) < 0) {
        this.gameover(x, y);
      }
      if (this.remaining === 0) {
        this.gameclear();
      }
      if (this.on_click_func) {
        this.on_click_func(x, y);
      }
      if (old_game_status !== this.game_status) {
        return this.on_game_status_changed();
      }
    };

    Minefield.prototype.on_rclick = function(x, y) {
      var old_game_status;

      old_game_status = this.game_status;
      if (this.game_status < 0) {
        return;
      }
      if (this.game_status === 1) {
        this.game_status = 0;
      }
      this.flag(x, y);
      if (this.on_rclick_func) {
        this.on_rclick_func(x, y);
      }
      if (old_game_status !== this.game_status) {
        return this.on_game_status_changed();
      }
    };

    Minefield.prototype.on_game_status_changed = function() {
      if (this.game_status_changed_func) {
        return this.game_status_changed_func(this.game_status);
      }
    };

    Minefield.prototype.start = function(x, y) {
      var nx, ny, _i, _ref, _results;

      this.game_status = 0;
      if (this.mines[x][y] === 0) {
        return;
      }
      _results = [];
      for (nx = _i = 0, _ref = this.columns - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; nx = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;

          _results1 = [];
          for (ny = _j = 0, _ref1 = this.rows - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; ny = 0 <= _ref1 ? ++_j : --_j) {
            if (this.mines[nx][ny] === 0) {
              this.mines = this.shift_table(this.mines, x - nx, y - ny);
              _results1.push(this.near_mines = this.generate_near_mines(this.mines));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Minefield.prototype.flag = function(x, y) {
      var n, nx, ny, td_class, _i, _len, _ref, _ref1;

      td_class = this.get_class(x, y);
      if (td_class !== null && !/^flag/.exec(td_class)) {
        return;
      }
      n = 1;
      if (this.flags[x][y] === this.max_mines) {
        n = -this.flags[x][y];
      }
      this.num_flags += n;
      this.flags[x][y] += n;
      _ref = this.near_positions(x, y);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], nx = _ref1[0], ny = _ref1[1];
        this.near_flags[nx][ny] += n;
      }
      if (n > 0) {
        return this.set_class(x, y, "flag-" + this.flags[x][y]);
      } else {
        return this.set_class(x, y, null);
      }
    };

    Minefield.prototype.press = function(x, y) {
      if (this.mines[x][y] > 0) {
        return -1;
      } else if (this.get_class(x, y) !== null) {
        return 1;
      }
      this.remaining -= 1;
      if (this.near_mines[x][y] === 0) {
        this.set_class(x, y, "empty");
      } else {
        this.set_class(x, y, "near-" + this.near_mines[x][y]);
      }
      return 0;
    };

    Minefield.prototype.expand = function(start_x, start_y) {
      var list, nx, ny, start_flags, start_mines, td_class, x, y, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4;

      td_class = this.get_class(start_x, start_y);
      if (td_class !== null && /^flag/.exec(td_class)) {
        return 1;
      }
      if (this.press(start_x, start_y) < 0) {
        return -1;
      }
      list = [[start_x, start_y]];
      start_mines = this.near_mines[start_x][start_y];
      start_flags = this.near_flags[start_x][start_y];
      if (start_mines === start_flags) {
        _ref = this.near_positions(start_x, start_y);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          _ref1 = _ref[_i], nx = _ref1[0], ny = _ref1[1];
          td_class = this.get_class(nx, ny);
          if (td_class === null) {
            list.push([nx, ny]);
            if (this.press(nx, ny) < 0) {
              return -1;
            }
          }
        }
      }
      while (list.length > 0) {
        _ref2 = list.pop(), x = _ref2[0], y = _ref2[1];
        if (this.near_mines[x][y] === 0) {
          _ref3 = this.near_positions(x, y);
          for (_j = 0, _len1 = _ref3.length; _j < _len1; _j++) {
            _ref4 = _ref3[_j], nx = _ref4[0], ny = _ref4[1];
            td_class = this.get_class(nx, ny);
            if (td_class === null) {
              list.push([nx, ny]);
              if (this.press(nx, ny) < 0) {
                return -1;
              }
            }
          }
        }
      }
      return 0;
    };

    Minefield.prototype.gameover = function(fail_x, fail_y) {
      var mine, x, y, _i, _ref, _results;

      this.game_status = -1;
      _results = [];
      for (y = _i = 0, _ref = this.rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;

          _results1 = [];
          for (x = _j = 0, _ref1 = this.columns - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
            mine = this.mines[x][y];
            if (mine > 0) {
              if (/^flag/.exec(this.get_class(x, y))) {
                continue;
              }
              this.set_class(x, y, "mine-" + mine);
              if (fail_x === x && fail_y === y) {
                _results1.push(this.set_class(x, y, "mine-exploded"));
              } else {
                _results1.push(void 0);
              }
            } else {
              if (this.flags[x][y] > 0) {
                _results1.push(this.set_class(x, y, "mine-wrong"));
              } else if (this.near_mines[x][y] === 0) {
                _results1.push(this.set_class(x, y, "empty"));
              } else {
                _results1.push(this.set_class(x, y, "near-" + this.near_mines[x][y]));
              }
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Minefield.prototype.gameclear = function() {
      return this.game_status = -2;
    };

    Minefield.prototype.stringify = function() {
      return JSON.stringify(this.mines);
    };

    return Minefield;

  })();

  window.Minefield = Minefield;

}).call(this);
